tickers_techs = ['FICO', 'AVGO', 'LRCX', 'NOW', 'ADBE', 'HUBS', 'MPWR', 'INTU',
                 'KLAC', 'SNPS', 'NVDA', 'MA', 'TYL', 'MSTR', 'MDB', 'CACI', 'IT',
                 'MSFT', 'ACN', 'ANSS', 'PAYC', 'MSI', 'ZBRA', 'LFUS', 'ADP',
                 'EPAM', 'CDNS', 'WDAY', 'PANW', 'CRM', 'ADSK', 'VRSN', 'NXPI',
                 'CDW', 'TEAM', 'WEX', 'AZPN', 'MANH', 'ADI', 'BR', 'AAPL', 'ANET',
                 'GLOB', 'JKHY', 'SPSC', 'APPF', 'BMI', 'ACLS', 'UI', 'TXN',
                 'MNDY', 'KEYS', 'FFIV', 'CYBR', 'VMW', 'OLED', 'SNOW', 'QLYS',
                 'CRWD', 'NSIT', 'PTC', 'IBM', 'ZS', 'SLAB', 'AMAT', 'SAP', 'ABNB',
                 'TEL', 'SITM', 'SHKP', 'ARW', 'GPN', 'FI', 'PAYX', 'SAIC', 'BAH',
                 'RVTY', 'OSIS', 'QCOM', 'ORCL', 'AEIS', 'ONTO', 'SWKS', 'AMD',
                 'BILL', 'IPGP', 'GRMN', 'WK', 'AKAM', 'QRVO', 'TER', 'SNX',
                 'SPLK', 'LDOS', 'ENTG', 'ON', 'MKSI', 'TSM', 'DDOG', 'SYNA',
                 'WIX', 'BDC', 'APH', 'LSCC', 'IDCC', 'EEFT', 'NEWR', 'POWI',
                 'GWRE', 'MCHP', 'CRUS', 'DIOD', 'MMS', 'DLB', 'NTAP', 'TTD', 'BKI',
                 'CDAY', 'BLKB', 'AMBA', 'OKTA', 'ITRI', 'FIVN', 'GDDY', 'CTSH',
                 'CVLT', 'ZD', 'LOGI', 'ZM', 'STX', 'PCOR', 'PLUS', 'MU', 'NET',
                 'ALTR', 'TWLO', 'PYPL', 'ALRM', 'SQ', 'FOUR', 'FTNT', 'PRGS',
                 'PI', 'ESTC', 'MRVL', 'NATI', 'DELL', 'FIS', 'SSNC', 'CSGS',
                 'SHOP', 'ENV', 'TRMB', 'PSN', 'WOLF', 'CSCO', 'BL', 'KLIC',
                 'RPD', 'LITE', 'DOCU', 'DAVA', 'CGNX', 'PEGA', 'SLP', 'APPN',
                 'BSY', 'AVT', 'DT', 'TENB', 'SPT', 'TDC', 'GTLB', 'WDC', 'CIEN',
                 'BFH', 'ALGM', 'SMAR', 'APP', 'NSSC', 'GLBE', 'COHU', 'PAR', 'PSTG',
                 'U', 'VPG', 'DOCN', 'PRO', 'VRNT', 'INTC', 'CFLT', 'VRT', 'ATEX',
                 'UCTT', 'QTWO', 'AI', 'HPQ', 'GLW', 'AOSL', 'MEI', 'FORM', 'CCSI',
                 'SQSP', 'DV', 'SPNS', 'FLYW', 'RAMP', 'VSAT', 'VRNS', 'RNG', 'BOX',
                 'RBLX', 'NTNX', 'NCNO', 'NCR', 'VNT', 'SCSC', 'AYX', 'NTCT', 'EXLS',
                 'DBX', 'JNPR', 'FROG', 'AMKR', 'CRNC', 'PINS', 'SMTC', 'TOST',
                 'RELY', 'ACIW', 'EVBG', 'MXL', 'CEVA', 'ASAN', 'GEN', 'TCX', 'DXC',
                 'FSLY', 'DCT', 'MLNK', 'XM', 'HPE', 'FARO', 'BMBL', 'KD', 'CRSR',
                 'LSPD', 'XRX', 'PATH', 'ATEN', 'RIOT', 'S', 'AFRM', 'PAY', 'UPWK',
                 'TTMI', 'NABL', 'STNE', 'PUBM', 'NTGR', 'SUMO', 'WU', 'SWI', 'DNB',
                 'BIGC', 'ZUO', 'TASK', 'PLTK', 'PAGS', 'SKLZ', 'APPS', 'YEXT',
                 'ALIGHT', 'GDRX', 'DDD', 'CLVT', 'OUST', 'CLSK', 'GDEV', 'LAZR',
                 'WISH', 'LPL', 'CGNT', 'LPSN', 'BLZE', 'VMEO', 'RSKD', 'TWOU',
                 'NOK', 'EGHT', 'MVIS', 'MTTR', 'TLS', 'TSP', 'INSG'
                ]

tickers_sc = ["MVIS", "KOPN", "QNST", "TLS", "APEI", "EGHT", "BLMN", "INSG", "AOSL",
              "WW", "CPS", "MLNK", "FNKO", "NABL", "OFIX", "PNTG", "HEAR", "VUZI",
              "UCTT", "BJRI", "ZUO", "FARO", "TTMI", "COHU", "EAT", "VPG", "FLWS",
              "PUBM", "ANDE", "WISH", "BH", "ATGE", "CVGW", "PETQ", "ARRY", "NSSC",
              "CNXN", "CCSI", "TWOU", "SFIX", "CRMT", "SPNS", "MHO", "GPRO", "CEVA",
              "ATEX", "PI", "SHEN", "VMEO", "YEXT", "PLUS", "MCRI", "SCSC", "ASTS",
              "SKLZ", "XNCR", "MEI", "WGO", "MSEX", "RELY", "CRNC", "BLNK", "CGNT",
              "SLP", "LPSN", "ATNI", "GTX", "IDCC", "MGPI", "ZUMZ", "HZO", "UDMY",
              "ATEN", "MED", "BIGC", "AAN", "MOV", "DRQ", "AOUT", "NTGR", "DLTH",
              "JBSS", "BZUN", "POSH", "RGR", "MFGP", "SUMO", "VLDR", "DM", "VERU",
              "LRN", "RCII", "GES", "FTCI", "JOUT", "EPC", "WKHS", "GCO", "BGS", "CLSK",
              "QUOT", "USNA", "ANAB", "TAL", "ETD", "OSIS", "THS", "XPEL", "CHEF",
              "JACK", "SBH", "MBUU", "STRA", "SLVM", "EVBG", "BAND", "UTL", "CARS",
              "AMCX", "ANF", "PRTS", "IRBT", "BIG", "HIBB", "APPH", "HCC", "VZIO",
              "LEGH", "METC", "WWW", "OSTK", "MOMO", "HYLN", "MNRO", "SNBR", "SOHU",
              "CDLX", "STEM", "PLCE", "QRTEA", "TTCF"
             ]

tickers_schealth = ['QNCX', 'GOSS', 'TCMD', 'BDTX', 'AXGN', 'BBIO', 'AUPH', 'RCUS',
                   'SKIN', 'ATRI', 'SRDX', 'NVRO', 'AMTI', 'ADPT', 'CYRX', 'ADUS',
                   'BCRX', 'ZYXI', 'HSKA', 'ANIK', 'VNDA', 'AMPH', 'EGRX', 'EAR',
                   'MLAB', 'ESPR', 'IRWD', 'CGEN', 'AVNS', 'MYGN', 'AWH', 'TCRR',
                   'MODV', 'ARCT', 'EMBC', 'CVM', 'HCAT', 'INVA', 'NVAX', 'AORT',
                   'FLGT', 'USPH', 'RETA', 'CSII', 'MDRX', 'AERI', 'KDNY', 'SDGR',
                   'EBS', 'GRPH', 'VREX', 'VCEL', 'MD', 'CHRS', 'TVTX', 'NVTA',
                   'RGNX', 'KIDS', 'NRIX', 'INGN', 'TWST', 'VCYT', 'HIMS', 'ALEC',
                   'ZYNE', 'ALXO', 'BLUE', 'VXRT', 'BNGO', 'ZIMV', 'FATE', 'CDNA',
                   'ORMP', 'MRVI', 'LGND', 'ANIP', 'ENTA', 'ATRA', 'CLOV', 'LYEL',
                   'BTAI', 'DMTK', 'RYTM', 'KOD', 'AGIO', 'NEO', 'TSVT', 'ARQT', 
                   'SAVA', 'AVXL', 'DCPH', 'ALLO', 'FULC', 'ZNTL', 'OSUR', 'TRHC',
                   'RXRX', 'CARA', 'SLDB', 'EDIT', 'ARVN', 'INO', 'APLT', 'ICPT',
                   'IGMS', 'AFMD', 'BYSI', 'SWTX', 'IOVA', 'GTHX', 'ALLK', 'SGMO',
                   'HRTX', 'AVIR', 'PRAX', 'NKTR', 'ALT'
                    ]

tickers_health = ["CTLT", "ARWR", "RARE", "DOCS", "TWST", "LFST", "NTRA",
                  "SKIN", "BMRN", "ENTA", "TXG", "HALO", "RGEN", "PEN", "TFX",
                  "AZTA", "AXNX", "MYGN", "PRTA", "PTCT", "TDOC", "BEAM", "DXCM",
                  "FATE", "CLVT", "SRCL", "GMED", "SYK", "ACAD", "REGN", "INMD",
                  "NBIX", "EVH", "PFE", "HAE", "RDY", "SYNH", "QGEN", "ISRG",
                  "VRTX", "EXEL", "LLY", "NVS", "ABBV", "BMY", "MRK", "HSIC",
                  "TMO", "HOLX", "ITGR", "RMD", "HUM", "ABT", "JNJ", "PGNY",
                  "MDT", "AMGN", "MASI", "EW", "ILMN", "CYTK", "ATRC", "SGEN",
                  "SNY", "CRSP", "BIIB", "OMCL", "NARI", "AMEH", "CORT", "SWAV",
                  "VEEV", "ABCL", "NTLA", "AXSM"
                 ]

tickers_energy = ["COP", "SR", "SWX", "CEG", "OGS", "VST", "NFE", "SWN",
                  "VTNR", "BE", "LNG", "OGE", "AMR", "MPC", "ENB", "ET",
                  "ARCH", "TRGP", "EQT", "CTRA", "OKE", "WMB", "CCJ", "ETRN",
                  "ENPH", "SJI", "KMI", "AM", "OVV", "INT", "PSX", "PBA",
                  "TTE", "VLO", "VET", "CLR", "SHEL", "XOM", "CNQ", "CVX",
                  "PDS", "REX", "MGY", "CNX", "PXD", "APA", "EOG", "HES",
                  "BLDP", "OXY", "PBF", "FTI", "SU", "PDCE", "FCEL", "UUUU",
                  "OII", "MRO", "HAL", "HP", "DK", "NOV", "PUMP", "GEVO",
                  "DVN", "CHX", "SLB", "RIG", "BKR", "WHD", "VAL", "OIS",
                  "CLB", "WTTR", "FANG", "MUR"
                 ]

tickers_commodity_stocks = ["KALU", "CE", "EXP", "ASIX", "CC", "EMN", "SRI", "DD", "SMG", "OI", "ALB", 
                            "ATI", "LAC", "BCC", "MTRN", "KWR", "NTR", "MTX", "X", "PPG", "OLN", "CMC",
                            "CBT", "SHW", "FCX", "AA", "AXTA", "CMP", "LYB", "MATV", "CLF", "WLK", "IOSP",
                            "MLM", "HUN", "SCL", "RS", "MOS", "BERY", "VMC", "AVNT", "RIO", "NEU", "FUL",
                            "IP", "IFF", "ECL", "WRK", "VALE", "VVV", "APD", "LIN", "ARNC", "ASH", "CTVA",
                            "STLD", "SEE", "MP", "NUE", "CF", "CCK", "FMC", "AMCR", "DOW", "GPK", "RPM",
                            "SQM", "SCCO", "GEF", "BCPC", "AVY", "SLGN", "ATR", "CRS", "MUSA", "AG", "LTHM",
                            "KGC", "BALL", "PAAS", "WPM", "UEC", "AEM", "NEM", "RGLD", "NGVT", "LICY"
                           ]

tickers_china = ['3888.HK', '0992.HK', '9868.HK', '1368.HK', '0700.HK', '0881.HK',
                 '2359.HK', '2020.HK', '1810.HK', '2518.HK', '9888.HK', '1929.HK',
                 '6618.HK', '2382.HK', '2333.HK', '0175.HK', '3690.HK', '1024.HK',
                 '2899.HK', '1997.HK', '9626.HK', '2313.HK', '0241.HK', '1171.HK',
                 '6969.HK', '9988.HK', '2238.HK', '2331.HK', '2015.HK', '9999.HK',
                 '0168.HK', '6881.HK', '1299.HK', '1919.HK', '9696.HK', '9618.HK',
                 '0388.HK', '3898.HK', '1044.HK', '0291.HK', '2269.HK', '0960.HK',
                 '0968.HK', '2319.HK', '2196.HK', '0016.HK', '1876.HK', '1066.HK',
                 '0836.HK', '6030.HK', '9633.HK', '2328.HK', '1347.HK', '0101.HK',
                 '2600.HK', '2202.HK', '1378.HK', '0788.HK', '3988.HK', '2007.HK',
                 '0027.HK', '0267.HK', '1288.HK', '6690.HK', '0688.HK', '0001.HK',
                 '1398.HK', '1113.HK', '1928.HK', '2388.HK', '0669.HK', '1038.HK',
                 '3968.HK', '2628.HK', '1177.HK', '0939.HK', '0868.HK', '1336.HK',
                 '0066.HK', '0012.HK', '6862.HK', '1109.HK', '0916.HK', '3908.HK',
                 '3800.HK', '0857.HK', '6185.HK', '6098.HK', '0003.HK', '0338.HK',
                 '0914.HK', '1385.HK', '1093.HK', '0386.HK', '0670.HK', '3692.HK',
                 '1061.HK', '2688.HK', '1099.HK', '2601.HK', '1898.HK', '2883.HK',
                 '1801.HK', '9995.HK', '0268.HK'
                ]

tickers_indexes = ['XU100.IS', '^IBEX', '^IBEX', '^SSMI', '^TECDAX', '^GDAXI', '^IMOEX', '^STOXX',
                     '^RUI', '^FTMC', '^BVSP', '^N225', '^BFX', '^FTSE', '^NDX', '^NYA',
                     '^HSCE', '^NSEI', '^FCHI', '^HSI', '^CASE', '^IXIC', '^DJUSSC', '^DJU',
                     '^DJT', '^DJITR', '^GSPC', '^MID', '^FTLC', '^DJI'
                     'ETRN', 'RIG', 'FCEL'
                  ]

tickers_commodity = ['OUSX', 'FCUSX', 'ZGUSD', 'ZIUSD', 'KWUSX', 'SMUSD', 'SUSX', 'CUSX',
                     'LCUSX', 'BOUSX', 'LHUSX', 'RRUSD', 'PLUSD', 'ZCUSX', 'KEUSX', 'ZOUSX',
                     'NGUSD', 'ZSUSX', 'OJUSX', 'HGUSD', 'GCUSD', 'LBUSD', 'HOUSD', 'CCUSD',
                     'CLUSD', 'KCUSX', 'RBUSD', 'SIUSD', 'CTUSX', 'PAUSD'
                    ]

tickers_allFMP = (tickers_techs + tickers_sc + tickers_schealth + tickers_health +
               tickers_energy + tickers_commodity_stocks + tickers_china +
               tickers_indexes + tickers_commodity)

tickers_crypto_KuCoinMain = ["ACH-USDT", "ADA-USDT", "AGIX-USDT", "ALGO-USDT", "APE-USDT", "APT-USDT", "ARB-USDT",
                             "ASTRA-USDT", "ATOM-USDT", "AVAX-USDT", "BCH-USDT", "BTC-USDT", "CFX-USDT", "CRO-USDT",
                             "DOGE-USDT", "DOT-USDT", "DYDX-USDT", "EOS-USDT", "ETC-USDT", "ETH-USDT", "FIL-USDT",
                             "FLUX-USDT", "FTM-USDT", "GALA-USDT", "GMT-USDT", "GRT-USDT", "HBAR-USDT", "HFT-USDT",
                             "ICP-USDT", "IMX-USDT", "INJ-USDT", "JASMY-USDT", "KCS-USDT", "KDA-USDT", "LDO-USDT",
                             "LINK-USDT", "LTC-USDT", "MAGIC-USDT", "MANA-USDT", "MATIC-USDT", "NEAR-USDT", "ONE-USDT",
                             "OP-USDT", "QNT-USDT", "RNDR-USDT", "ROSE-USDT", "SAND-USDT", "SFUND-USDT", "SHIB-USDT",
                             "SNX-USDT", "SOL-USDT", "STX-USDT", "TON-USDT", "TRX-USDT", "UNI-USDT", "USDC-USDT", "VELO-USDT",
                             "VET-USDT", "VRA-USDT", "XCN-USDT", "XLM-USDT", "XMR-USDT", "XRP-USDT", "ZEC-USDT"
                            ]

tickers_crypto_KuCoinOther = ["1INCH-USDT", "2CRZ-USDT", "AAVE-USDT", "ABBC-USDT", "ACA-USDT", "ACE-USDT", "ACOIN-USDT",
                              "ACQ-USDT", "ACS-USDT", "ACT-USDT", "ADS-USDT", "ADX-USDT", "AERGO-USDT", "AFK-USDT",
                              "AGLD-USDT", "AI-USDT", "AIOZ-USDT", "AIPAD-USDT", "AKRO-USDT", "AKT-USDT", "ALEPH-USDT",
                              "ALGO-USDT", "ALICE-USDT", "ALPHA-USDT", "ALPINE-USDT", "ALT-USDT", "AMB-USDT", "AMP-USDT",
                              "AMPL-USDT", "ANC-USDT", "ANKR-USDT", "ANT-USDT", "AOA-USDT", "AOG-USDT", "API3-USDT",
                              "APL-USDT", "AR-USDT", "ARKER-USDT", "ARNM-USDT", "ARPA-USDT", "ARRR-USDT", "ARX-USDT",
                              "ASD-USDT", "ASTR-USDT", "ATA-USDT", "ATOM-USDT", "AUDIO-USDT", "AURORA-USDT", "AURY-USDT",
                              "AVA-USDT", "AXS-USDT", "AZERO-USDT", "BAL-USDT", "BAND-USDT", "BAT-USDT", "BAX-USDT",
                              "BBC-USDT", "BDX-USDT", "BEAT-USDT", "BERPO-USDT", "BFC-USDT", "BICO-USDT", "BIFI-USDT",
                              "BLOK-USDT", "BLUR-USDT", "BLZ-USDT", "BNB-USDT", "BNC-USDT", "BNS-USDT", "BOA-USDT",
                              "BOB-USDT", "BOBA-USDT", "BOLT-USDT", "BOND-USDT", "BONDLY-USDT", "BOSON-USDT", "BRISE-USDT",
                              "BRWL-USDT", "BSV-USDT", "BSW-USDT", "BTT-USDT", "BULL-USDT", "BURGER-USDT", "BUSD-USDT",
                              "BUX-USDT", "BUY-USDT", "C98-USDT", "CAKE-USDT", "CARD-USDT", "CARE-USDT", "CAS-USDT",
                              "CCD-USDT", "CEEK-USDT", "CELO-USDT", "CELR-USDT", "CERE-USDT", "CETUS-USDT", "CFG-USDT",
                              "CGG-USDT", "CGPT-USDT", "CHMB-USDT", "CHR-USDT", "CHZ-USDT", "CIRUS-USDT", "CIX100-USDT",
                              "CKB-USDT", "CLH-USDT", "CLUB-USDT", "CLV-USDT", "CMP-USDT", "COCOS-USDT", "COMP-USDT",
                              "COOHA-USDT", "COTI-USDT", "COV-USDT", "CPOOL-USDT", "CQT-USDT", "CREAM-USDT", "CREDI-USDT",
                              "CRPT-USDT", "CRV-USDT", "CSIX-USDT", "CSPR-USDT", "CTC-USDT", "CTI-USDT", "CTSI-USDT",
                              "CUDOS-USDT", "CULT-USDT", "CVX-USDT", "CWAR-USDT", "CWEB-USDT", "CWS-USDT", "DAG-USDT",
                              "DAO-USDT", "DAPPT-USDT", "DAPPX-USDT", "DAR-USDT", "DASH-USDT", "DATA-USDT", "DC-USDT",
                              "DEGO-USDT", "DERC-USDT", "DERO-USDT", "DEXE-USDT", "DFA-USDT", "DFI-USDT", "DFYN-USDT",
                              "DG-USDT", "DGB-USDT", "DIA-USDT", "DIVI-USDT", "DMTR-USDT", "DODO-USDT", "DOSE-USDT",
                              "DOT-USDT", "DPET-USDT", "DPR-USDT", "DPX-USDT", "DREAMS-USDT", "DSLA-USDT", "DUSK-USDT",
                              "DVPN-USDT", "DYP-USDT", "ECOX-USDT", "EFI-USDT", "EFX-USDT", "EGAME-USDT", "EGLD-USDT",
                              "ELA-USDT", "ELON-USDT", "ENJ-USDT", "ENQ-USDT", "ENS-USDT", "EOSC-USDT", "EPIK-USDT",
                              "EPK-USDT", "EPX-USDT", "EQX-USDT", "EQZ-USDT", "ERG-USDT", "ERN-USDT", "ERSDL-USDT",
                              "ERTHA-USDT", "ETHW-USDT", "ETN-USDT", "EUL-USDT", "EVER-USDT", "EWT-USDT", "FALCONS-USDT",
                              "FCON-USDT", "FEAR-USDT", "FET-USDT", "FIDA-USDT", "FITFI-USDT", "FKX-USDT", "FLAME-USDT",
                              "FLOKI-USDT", "FLOW-USDT", "FLR-USDT", "FLY-USDT", "FORESTPLUS-USDT", "FORM-USDT", "FORT-USDT",
                              "FORTH-USDT", "FRA-USDT", "FRM-USDT", "FRONT-USDT", "FRR-USDT", "FSN-USDT", "FT-USDT",
                              "FTG-USDT", "FTT-USDT", "FXS-USDT", "GAFI-USDT", "GAL-USDT", "GARI-USDT", "GAS-USDT",
                              "GEEQ-USDT", "GEM-USDT", "GENS-USDT", "GFT-USDT", "GGG-USDT", "GHX-USDT", "GLCH-USDT",
                              "GLM-USDT", "GLMR-USDT", "GLQ-USDT", "GMB-USDT", "GMEE-USDT", "GMM-USDT", "GMX-USDT",
                              "GNS-USDT", "GOAL-USDT", "GODS-USDT", "GOVI-USDT", "GPT-USDT", "GRAIL-USDT", "GST-USDT",
                              "GTC-USDT", "H2O-USDT", "H3RO3S-USDT", "HAI-USDT", "HAKA-USDT", "HALO-USDT", "HAPI-USDT",
                              "HARD-USDT", "HAWK-USDT", "HBB-USDT", "HEART-USDT", "HEGIC-USDT", "HERO-USDT", "HIAZUKI-USDT",
                              "HIFI-USDT", "HIGH-USDT", "HIOD-USDT", "HMND-USDT", "HNT-USDT", "HOTCROSS-USDT", "HT-USDT",
                              "HTR-USDT", "HYDRA-USDT", "HYVE", "ICX-USDT", "ID-USDT", "IDEA-USDT", "IGU-USDT", "IHC-USDT",
                              "ILA-USDT", "ILV-USDT", "IOI-USDT", "IOST-USDT", "IOTA-USDT", "IOTX-USDT", "IRON-USDT",
                              "ISP-USDT", "IXS-USDT", "IZI-USDT", "JAM-USDT", "JAR-USDT", "JASMY-USDT", "JST-USDT",
                              "KAGI-USDT", "KAI-USDT", "KAR-USDT", "KARATE-USDT", "KAS-USDT", "KAT-USDT", "KAVA-USDT",
                              "KCS-USDT", "KDA-USDT", "KDON-USDT", "KICKS-USDT", "KING-USDT", "KLAY-USDT", "KLV-USDT",
                              "KMA-USDT", "KMD-USDT", "KNC-USDT", "KOK-USDT", "KOL-USDT", "KONO-USDT", "KRL-USDT", "KSM-USDT",
                              "LABS-USDT", "LACE-USDT", "LADYS-USDT", "LAVAX-USDT", "LAYER-USDT", "LBP-USDT", "LIKE-USDT",
                              "LINA-USDT", "LIT-USDT", "LITH-USDT", "LMR-USDT", "LMWR-USDT", "LOC-USDT", "LOCG-USDT",
                              "LOCUS-USDT", "LOKA-USDT", "LOOKS-USDT", "LPOOL-USDT", "LPT-USDT", "LQTY-USDT", "LRC-USDT",
                              "LSS-USDT", "LTO-USDT", "LTX-USDT", "LYM-USDT", "LYXe-USDT", "MAHA-USDT", "MAKI-USDT",
                              "MAN-USDT", "MAP-USDT", "MARS4-USDT", "MARSH-USDT", "MASK-USDT", "MATTER-USDT", "MBL-USDT",
                              "MC-USDT", "MELOS-USDT", "MEM-USDT", "METIS-USDT", "MINA-USDT", "MIR-USDT", "MITX-USDT",
                              "MJT-USDT", "MKR-USDT", "MLK-USDT", "MLN-USDT", "MLS-USDT", "MNET-USDT", "MNST-USDT",
                              "MNW-USDT", "MODEFI-USDT", "MONI-USDT", "MOOV-USDT", "MOVR-USDT", "MPLX-USDT", "MSWAP-USDT",
                              "MTL-USDT", "MTRG-USDT", "MTS-USDT", "MTV-USDT", "MV-USDT", "MXC-USDT", "MYRIA-USDT",
                              "NAKA-USDT", "NAVI-USDT", "NDAU-USDT", "NEER-USDT", "NEO-USDT", "NFT-USDT", "NGC-USDT",
                              "NGL-USDT", "NHCT-USDT", "NIM-USDT", "NKN-USDT", "NMR-USDT", "NOIA-USDT", "NOM-USDT",
                              "NORD-USDT", "NRFB-USDT", "NTVRK-USDT", "NUM-USDT", "NWC-USDT", "NXRA-USDT", "NYM-USDT",
                              "OAS-USDT", "OCEAN-USDT", "ODDZ-USDT", "OGN-USDT", "OGV-USDT", "OLE-USDT", "OLT-USDT",
                              "OM-USDT", "OMG-USDT", "ONSTON-USDT", "ONT-USDT", "OOE-USDT", "OPCT-USDT", "OPUL-USDT",
                              "ORAI-USDT", "ORBS-USDT", "ORN-USDT", "OSMO-USDT", "OTK-USDT", "OUSD-USDT", "OVR-USDT",
                              "OXEN-USDT", "OXT-USDT", "P00LS-USDT", "PAXG-USDT", "PBR-USDT", "PBX-USDT", "PCX-USDT",
                              "PDEX-USDT", "PEEL-USDT", "PEL-USDT", "PEOPLE-USDT", "PEPE-USDT", "PERP-USDT", "PHA-USDT",
                              "PHNX-USDT", "PIAS-USDT", "PIX-USDT", "PKF-USDT", "PLD-USDT", "PLGR-USDT", "PLU-USDT",
                              "PLY-USDT", "PMON-USDT", "PNT-USDT", "POKT-USDT", "POL-USDT", "POLC-USDT", "POLK-USDT",
                              "POLS-USDT", "POLX-USDT", "POND-USDT", "POSI-USDT", "PRE-USDT", "PRIMAL-USDT", "PRMX-USDT",
                              "PROM-USDT", "PRQ-USDT", "PSL-USDT", "PSTAKE-USDT", "PUMLX-USDT", "PUNDIX-USDT", "PUSH-USDT",
                              "PYR-USDT", "PZP-USDT", "QI-USDT", "QRDO-USDT", "QUARTZ-USDT", "QUICK-USDT", "RACA-USDT",
                              "RACEFI-USDT", "RANKER-USDT", "RBP-USDT", "RDNT-USDT", "REAP-USDT", "RED-USDT", "REEF-USDT",
                              "REN-USDT", "REQ-USDT", "REV-USDT", "REVU-USDT", "REVV-USDT", "RFOX-USDT", "RFUEL-USDT",
                              "RLC-USDT", "RLTM-USDT", "RLY-USDT", "RMRK-USDT", "ROAR-USDT", "ROUTE-USDT", "RPL-USDT",
                              "RSR-USDT", "RUNE-USDT", "RVN-USDT", "SCLP-USDT", "SCRT-USDT", "SD-USDT", "SDAO-USDT",
                              "SDL-USDT", "SENSO-USDT", "SFP-USDT", "SHA-USDT", "SHILL-USDT", "SHR-USDT", "SHX-USDT",
                              "SIDUS-USDT", "SIMP-USDT", "SIN-USDT", "SKEY-USDT", "SKL-USDT", "SKU-USDT", "SLCL-USDT",
                              "SLIM-USDT", "SLP-USDT", "SOLR-USDT", "SOLVE-USDT", "SON-USDT", "SOS-USDT", "SOUL-USDT",
                              "SPA-USDT", "SRBP-USDT", "SRK-USDT", "SRM-USDT", "SSV-USDT", "STARLY-USDT", "STC-USDT",
                              "STEPWATCH-USDT", "STG-USDT", "STND-USDT", "STORE-USDT", "STORJ-USDT", "STRAX-USDT",
                              "STRONG-USDT", "SUI-USDT", "SUIA-USDT", "SUIP-USDT", "SUKU-USDT", "SUN-USDT", "SUPER-USDT",
                              "SUSHI-USDT", "SUTER-USDT", "SWASH-USDT", "SWEAT-USDT", "SWFTC-USDT", "SWINGBY-USDT",
                              "SWP-USDT", "SXP-USDT", "SYLO-USDT", "SYN-USDT", "SYNR-USDT", "SYS-USDT", "T-USDT", "TARA-USDT",
                              "TAUM-USDT", "TEL-USDT", "TEM-USDT", "TFUEL-USDT", "THETA-USDT", "TIDAL-USDT", "TIME-USDT",
                              "TITAN-USDT", "TLM-USDT", "TLOS-USDT", "TOKO-USDT", "TONE-USDT", "TOWER-USDT", "TRAC-USDT",
                              "TRADE-USDT", "TRB-USDT", "TRIAS-USDT", "TRIBE-USDT", "TRIBL-USDT", "TRU-USDT", "TRVL-USDT",
                              "TT-USDT", "TURBOS-USDT", "TVK-USDT", "TWT-USDT", "TXA-USDT", "UBX-USDT", "UFO-USDT",
                              "UMA-USDT", "UNB-USDT", "UNFI-USDT", "UNIC-USDT", "UNO-USDT", "UOS-USDT", "UPO-USDT",
                              "URUS-USDT", "USDD-USDT", "VAI-USDT", "VEED-USDT", "VEGA-USDT", "VEMP-USDT", "VID-USDT",
                              "VIDT-USDT", "VISION-USDT", "VLX-USDT", "VOXEL-USDT", "VR-USDT", "VSYS-USDT", "VXV-USDT",
                              "WAL-USDT", "WAVES-USDT", "WAXL-USDT", "WAXP-USDT", "WELL-USDT", "WEMIX-USDT", "WEST-USDT",
                              "WHALE-USDT", "WILD-USDT", "WIN-USDT", "WLKN-USDT", "WMT-USDT", "WOM-USDT", "WOMBAT-USDT",
                              "WOO-USDT", "WOOP-USDT", "WRX-USDT", "WSIENNA-USDT", "XAVA-USDT", "XCAD-USDT", "XCH-USDT",
                              "XCUR-USDT", "XCV-USDT", "XDB-USDT", "XDC-USDT", "XDEFI-USDT", "XEC-USDT", "XED-USDT",
                              "XEM-USDT", "XETA-USDT", "XHV-USDT", "XNL-USDT", "XNO-USDT", "XPR-USDT", "XPRT-USDT",
                              "XRD-USDT", "XTAG-USDT", "XTM-USDT", "XTZ-USDT", "XWG-USDT", "XYM-USDT", "XYO-USDT",
                              "YFDAI-USDT", "YFI-USDT", "YGG-USDT", "YLD-USDT", "ZBC-USDT", "ZCX-USDT", "ZEE-USDT", 
                              "ZEN-USDT", "ZIL-USDT", "ZKT-USDT", "ZPAY-USDT"
                             ]

tickers_crypto_KuCoinAll = tickers_crypto_KuCoinMain + tickers_crypto_KuCoinOther

